version: "3"

services:
  topic_selector2:
    container_name: topic-selector-2
    restart: always
    build: .
    volumes:
      - ".:/app"
    ports:
      - "8050:8050"
    command: tail -f /dev/null
